name : CI/CD Pipeline
on:
push:
branches:
  - main
pull_request:
branches:
- main

permissions:
pull_request: write
contents: write

jobs:
# Code has been linted
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    -name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8 black isort bandit
        pip install -r requirements.txt

#Testing
test:
needs: [lint]
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Set up Python 3.x
  uses: actions/setup-python@v3
  with:
    python-version: "3.x"

- name: Install dependencies
  run: |
    python3 -m pip install --upgrade pip
    pip install flake8 black isort bandit
    pip install -r requirements.txt